apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: basic-flink-example
  namespace: flink
spec:
  image: flink:1.20
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  podTemplate:
    spec:
      containers:
      - name: flink-main-container
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: basic-flink-example
