apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flink-metrics
  namespace: monitoring
  labels:
    app: flink
spec:
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics  # Flink exposes Prometheus metrics on port 9249 by default
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flink-taskmanager-metrics
  namespace: monitoring
  labels:
    app: flink-taskmanager
spec:
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s