apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: singleuser-spark
  namespace: jupyter
spec:
  podSelector:
    matchLabels:
      component: singleuser-server
  policyTypes:
  - Egress
  egress:
  - {}  # Allow all egress
