apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-spark
  namespace: jupyter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyter-spark-role
  namespace: jupyter
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyter-spark-rolebinding
  namespace: jupyter
subjects:
- kind: ServiceAccount
  name: jupyter-spark
  namespace: jupyter
roleRef:
  kind: Role
  name: jupyter-spark-role
  apiGroup: rbac.authorization.k8s.io
