apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset-redis
  namespace: superset
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: superset-redis
    template:
      type: Opaque
      data:
        redis-password: "{{ .password }}"
  dataFrom:
    - extract:
        key: kv/redis