apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset-env
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: superset-env             # <-- the K8s Secret Superset will read
    template:
      type: Opaque
      data:
        SUPERSET_SECRET_KEY: "{{ .SECRET_KEY }}"          # from Vault
        SUPERSET_DATABASE_PASSWORD: "{{ .password }}"     # from Vault
  dataFrom:
    - extract:
        key: superset