apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-env
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: superset-env
  data:
    # Map Vault keys to the expected Kubernetes secret keys
    - secretKey: DB_PASS           # Superset expects this
      remoteRef:
        key: kv/superset
        property: password         # Vault has this
    - secretKey: SUPERSET_SECRET_KEY  # Superset expects this
      remoteRef:
        key: kv/superset
        property: SECRET_KEY       # Vault has this
    # Keep the static values
    - secretKey: DB_HOST
      remoteRef:
        key: kv/superset
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: kv/superset
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: kv/superset
        property: DB_USER
    - secretKey: DB_NAME
      remoteRef:
        key: kv/superset
        property: DB_NAME