apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset-redis
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: superset-redis
    template:
      type: Opaque
      data:
        redis-password: "{{ .password }}"  # <--- change if your Vault field differs
  dataFrom:
    - extract:
        key: kv/redis                      # <--- set to your actual Vault path