dbt_project:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      database: "{{ env_var('POSTGRES_DB') }}"
      schema: streaming
      threads: 4
  target: dev
