FROM python:3.10-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir kafka-python psycopg2-binary

# Copy consumer script
COPY kafka_consumer/consumer.py /app/consumer.py

CMD ["python", "consumer.py"]