FROM python:3.10-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir kafka-python

# Copy producer script
COPY kafka_producer/producer.py /app/producer.py

CMD ["python", "producer.py"]