apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-env
  namespace: metabase
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: metabase-env
  dataFrom:
    - extract:
        key: kv/metabase