apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
spec:
  clusterIP: None
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP
