apiVersion: external-secrets.io/v1  # <--- CHANGED from v1beta1
kind: ExternalSecret
metadata:
  name: jupyter-ai-google-secrets
  namespace: jupyter
spec:
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: jupyter-ai-google-secrets
    creationPolicy: Owner
  data:
  - secretKey: google-api-key
    remoteRef:
      key: kv/jupyter
      property: gemini-api-key