apiVersion: external-secrets.io/v1beta1 # Note: v1beta1 is the most common stable API. If v1 works, feel free to use it.
kind: ExternalSecret
metadata:
  name: jupyter-ai-google-secrets
  namespace: jupyter
spec:
  # 1. TELL EXTERNAL SECRETS WHICH STORE TO USE
  # You must update 'vault-backend' to the name of
  # your SecretStore or ClusterSecretStore resource.
  secretStoreRef:
    name: vault 
    kind: SecretStore    # Or ClusterSecretStore

  # 2. DEFINE THE OUTPUT KUBERNETES SECRET
  # This is what the operator will create
  target:
    name: jupyter-ai-google-secrets
    creationPolicy: Owner

  # 3. MAP DATA FROM VAULT TO THE K8S SECRET
  data:
  - secretKey: google-api-key # This is the key that will be in the K8s secret
    remoteRef:
      key: secret/data/jupyter  # The path in Vault you used in Step 1
      property: gemini-api-key  # The key within that path