apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unity-catalog-minio-credentials
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: unity-catalog-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/unity-catalog/minio
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: secret/unity-catalog/minio
        property: secretKey