apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unity-catalog-db-password
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: unity-catalog-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/unity-catalog/postgresql
        property: password