apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unity-catalog-db-password
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: unity-catalog-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/unity-catalog/postgresql
        property: password