apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-connections
  namespace: airflow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: airflow-connections
    creationPolicy: Owner
  refreshInterval: 1h
  data:
    # MinIO connection - Airflow will auto-create 'minio_default' connection
    - secretKey: AIRFLOW_CONN_MINIO_DEFAULT
      remoteRef:
        key: airflow
        property: minio-connection
    
    # Postgres connection - Airflow will auto-create 'postgres_default' connection
    - secretKey: AIRFLOW_CONN_POSTGRES_DEFAULT
      remoteRef:
        key: airflow
        property: postgres-connection
    
    # Trino connection - Airflow will auto-create 'trino_default' connection
    - secretKey: AIRFLOW_CONN_TRINO_DEFAULT
      remoteRef:
        key: airflow
        property: trino-connection
    
    # Spark connection - Airflow will auto-create 'spark_default' connection
    - secretKey: AIRFLOW_CONN_SPARK_DEFAULT
      remoteRef:
        key: airflow
        property: spark-connection
