apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.16.0
    helm:
      values: |
        executor: KubernetesExecutor
        postgresql:
          enabled: false
        externalDatabase:
          type: postgres
          host: 172.16.0.20
          port: 5432
          database: airflow
          user: airflow
          passwordSecret: airflow-postgres
          passwordSecretKey: password
        webserver:
          service:
            type: ClusterIP
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
