apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.coder.com/v2
    chart: coder
    targetRevision: 2.18.4
    helm:
      values: |
        coder:
          env:
            - name: CODER_ACCESS_URL
              value: "https://coder.tpomaville.com"
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-db-url
                  key: url
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: coder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
