apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tpomavil46/k8s-data-platform.git
    targetRevision: main
    path: apps/flink
  destination:
    server: https://kubernetes.default.svc
    namespace: flink
  syncPolicy:
    automated: {}   # no auto-sync
    syncOptions:
      - CreateNamespace=true
  # !!! SAFE MODE: do not prune/delete anything Argo doesn't own
  ignoreDifferences: []
