apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tpomavil46/k8s-data-platform.git
    targetRevision: main
    path: kubernetes/flink-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: flink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
