apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://downloads.apache.org/flink/flink-kubernetes-operator-1.10.0/
    chart: flink-kubernetes-operator
    targetRevision: 1.10.0
    helm:
      values: |
        operatorNamespaces:
          - flink
        metrics:
          port: 9999
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
