apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://hub.jupyter.org/helm-chart/
    chart: jupyterhub
    targetRevision: 3.3.8
    helm:
      skipSchemaValidation: true
      values: |
        proxy:
          service:
            type: ClusterIP

        singleuser:
          defaultUrl: "/lab"
          image:
            name: ghcr.io/tpomavil46/jupyter-spark
            tag: "latest"
            pullPolicy: Always
          storage:
            dynamic:
              storageClass: managed-nfs-storage
              pvcNameTemplate: claim-{username}
            capacity: 10Gi
          startTimeout: 600
          cpu:
            limit: 2
            guarantee: 0.1
          memory:
            limit: 4G
            guarantee: 512M
          serviceAccountName: jupyter-spark
          
          # === JUPYTER AI (GEMINI) CONFIGURATION ===
          # This block provides the API key and default model to the
          # single-user pod, which allows the jupyter-ai backend to start.
          extraEnv:
            # 1. Mounts the Google API Key from the k8s secret
            GOOGLE_API_KEY:
              valueFrom:
                secretKeyRef:
                  # This secret must be created in the 'jupyter' namespace
                  # by your ExternalSecret
                  name: jupyter-ai-google-secrets
                  key: google-api-key
            
            # 2. Tells jupyter-ai which model to use by default
            JUPYTER_AI_DEFAULT_MODEL: "google:gemini-1.5-flash"
          # === END JUPYTER AI CONFIGURATION ===

        # 👇 Disable the failing pre-pull hook so Argo can go Healthy
        prePuller:
          hook:
            enabled: false
          continuous:
            enabled: false

        hub:
          config:
            JupyterHub:
              authenticator_class: github
              authenticate_prometheus: False
            GitHubOAuthenticator:
              client_id: dummy
              client_secret: dummy
              oauth_callback_url: https://jupyter.tpomaville.com/hub/oauth_callback
              allowed_organizations: []
              allowed_users:
                - tpomavil46
              admin_users:
                - tpomavil46
              scope:
                - read:user
          extraEnv:
            OAUTH_CLIENT_ID:
              valueFrom:
                secretKeyRef:
                  name: jupyterhub-github-oauth
                  key: client-id
            OAUTH_CLIENT_SECRET:
              valueFrom:
                secretKeyRef:
                  name: jupyterhub-github-oauth
                  key: client-secret
          extraConfig:
            auth: |
              from oauthenticator.github import GitHubOAuthenticator
              c.JupyterHub.authenticator_class = GitHubOAuthenticator
              # --- THIS IS THE CORRECTED LINE ---
              c.GitHubOAuthenticator.client_id = os.environ.get('OAUTH_CLIENT_ID')
              # --- END CORRECTION ---
              c.GitHubOAuthenticator.client_secret = os.environ.get('OAUTH_CLIENT_SECRET')
              c.GitHubOAuthenticator.oauth_callback_url = 'https://jupyter.tpomaville.com/hub/oauth_callback'
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true