apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://d3nt0h.github.io/kafka-helm-charts
    chart: kafka
    targetRevision: 18.0.1
    helm:
      values: |
        replicas: 3
        persistence:
          enabled: true
          size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
