apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 30.1.6
    helm:
      values: |
        controller:
          replicaCount: 3
        persistence:
          enabled: true
          size: 20Gi
        image:
          repository: docker.io/bitnami/kafka
          tag: 3.9.0-debian-12-r3
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
