apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metabase
  source:
    repoURL: https://helm.metabase.com
    chart: metabase
    targetRevision: 0.10.0
    helm:
      values: |
        # Use environment variables from our secret
        envFrom:
          - secretRef:
              name: metabase-env
        
        # Additional required env vars
        extraEnvVars:
          - name: MB_DB_TYPE
            value: postgresql
        
        service:
          type: ClusterIP
          port: 80
          targetPort: 3000
        
        ingress:
          enabled: false