apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metabase
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: metabase
    targetRevision: 14.1.3
    helm:
      values: |
        postgresql:
          enabled: false
        
        existingSecret: metabase-env
        
        service:
          type: ClusterIP
          port: 80
        
        ingress:
          enabled: false
        
        metrics:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true