apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-demo-dbt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tpomavil46/k8s-data-platform.git
    targetRevision: main
    path: projects/streaming_demo/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: streaming-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
