apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    helm:
      values: |
        postgresql:
          enabled: false

        # We bring our own Secret via External Secrets → don't let the chart create one
        secretEnv:
          create: false

        # Wire exact keys explicitly from the Secret created by ESO
        extraEnv:
          - name: SUPERSET_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: superset-env
                key: SUPERSET_SECRET_KEY
          - name: SUPERSET_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: superset-env
                key: SUPERSET_DATABASE_PASSWORD
          - name: SUPERSET_LOAD_EXAMPLES
            value: "no"

        # Disable Redis & Celery for now so we can bring up web cleanly
        redis:
          enabled: false
        worker:
          enabled: false
        beat:
          enabled: false

        supersetNode:
          connections:
            db_host: "172.16.0.20"
            db_port: "5432"
            db_user: "superset"
            db_name: "superset"

        # Make sure Superset reads SECRET_KEY from env
        configOverrides:
          00_secrets_and_db.py: |
            import os
            SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
            SQLALCHEMY_DATABASE_URI = os.getenv("SUPERSET_DATABASE_URI")
            if not SQLALCHEMY_DATABASE_URI:
                user = os.getenv("SUPERSET_DATABASE_USER", "{{ .Values.supersetNode.connections.db_user }}")
                pwd  = os.getenv("SUPERSET_DATABASE_PASSWORD", "")
                host = "{{ .Values.supersetNode.connections.db_host }}"
                port = "{{ .Values.supersetNode.connections.db_port }}"
                name = "{{ .Values.supersetNode.connections.db_name }}"
                SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{user}:{pwd}@{host}:{port}/{name}"

        init:
          adminUser:
            username: admin
            password: admin
            email: tpomavil@icloud.com

        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true