apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    helm:
      values: |
        postgresql:
          enabled: false

        # Bring-your-own secret from ESO
        secretEnv:
          create: false
        envFromSecret: superset-env   # loads SUPERSET_SECRET_KEY + SUPERSET_DATABASE_URI

        # Keep workers off for first boot
        redis:
          enabled: false
        worker:
          enabled: false
        beat:
          enabled: false

        # Optional: keep these to document where your DB lives, but they’re not required
        supersetNode:
          connections:
            db_host: "172.16.0.20"
            db_port: "5432"
            db_user: "superset"
            db_name: "superset"

        # Config: just read from env
        configOverrides:
          00_secrets_and_db.py: |
            import os
            SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
            SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_DATABASE_URI"]

        init:
          adminUser:
            username: admin
            password: admin
            email: admin@superset.com

        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true