apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: superset
    targetRevision: 5.0.0
    helm:
      parameters: []   # values-only so defaults don’t sneak back
      values: |
        global:
          imageRegistry: docker.io

        postgresql:
          enabled: false
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 16.4.0
          primary:
            image:
              registry: docker.io
              repository: bitnami/postgresql
              tag: 16.4.0

        redis:
          enabled: false
          image:
            registry: docker.io
            repository: bitnami/redis
            tag: 7.2.4

        defaultInitContainers:
          waitForDB:
            enabled: false
          waitForRedis:
            enabled: false

        externalDatabase:
          host: 172.16.0.20
          port: 5432
          user: superset
          database: superset
          passwordSecret: superset-externaldb
          passwordSecretKey: db-password

        web:
          replicaCount: 1
          resources:
            requests:
              cpu: 10m
              memory: 128Mi

        worker:
          enabled: false

        scheduler:
          enabled: false