apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    helm:
      values: |
        postgresql:
          enabled: false

        # Pull SECRET_KEY + DB password from the K8s Secret made by ExternalSecrets
        envFromSecret: superset-env

        # Minimal explicit fields (user/db/host/port). Password is from env above.
        supersetNode:
          connections:
            db_host: "172.16.0.20"
            db_port: "5432"
            db_user: "superset"
            db_name: "superset"

        # Ensure Superset sees SECRET_KEY from env
        configOverrides:
          00_secret_key.py: |
            import os
            SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY")

          01_db_uri.py: |
            import os
            SQLALCHEMY_DATABASE_URI = os.getenv("SUPERSET_DATABASE_URI")
            if not SQLALCHEMY_DATABASE_URI:
                user = os.getenv("SUPERSET_DATABASE_USER", "{{ .Values.supersetNode.connections.db_user }}")
                pwd  = os.getenv("SUPERSET_DATABASE_PASSWORD", "")
                host = "{{ .Values.supersetNode.connections.db_host }}"
                port = "{{ .Values.supersetNode.connections.db_port }}"
                name = "{{ .Values.supersetNode.connections.db_name }}"
                SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{user}:{pwd}@{host}:{port}/{name}"

        # Seed admin for first login (move to Vault later if you like)
        init:
          adminUser:
            username: admin
            password: admin
            email: admin@superset.com

        extraEnv:
          - name: SUPERSET_LOAD_EXAMPLES
            value: "no"

        # TEMPORARILY disable Redis + Celery worker/beat so web can start now
        redis:
          enabled: false

        worker:
          enabled: false

        beat:
          enabled: false

        ingress:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true