apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    helm:
      values: |
        # Use built-in PostgreSQL
        postgresql:
          enabled: true
          auth:
            username: superset
            password: "superset-password"
            database: superset

        # DISABLE Redis completely - it's causing all the problems
        redis:
          enabled: false

        # Disable workers
        worker:
          enabled: false
        beat:
          enabled: false

        # Force a clean configuration that DISABLES Redis
        configOverrides:
          secret: |
            SECRET_KEY = "temporary-secret-key-change-me-later"
            # Explicitly disable all Redis/cache configurations
            CACHE_CONFIG = {
                'CACHE_TYPE': 'SimpleCache',
                'CACHE_DEFAULT_TIMEOUT': 300
            }
            DATA_CACHE_CONFIG = {
                'CACHE_TYPE': 'SimpleCache', 
                'CACHE_DEFAULT_TIMEOUT': 300
            }
            FILTER_STATE_CACHE_CONFIG = {
                'CACHE_TYPE': 'SimpleCache',
                'CACHE_DEFAULT_TIMEOUT': 300
            }
            EXPLORE_FORM_DATA_CACHE_CONFIG = {
                'CACHE_TYPE': 'SimpleCache',
                'CACHE_DEFAULT_TIMEOUT': 300
            }
            RESULTS_BACKEND = None

        # Disable init for now
        init:
          enabled: false

        ingress:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true