apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    helm:
      values: |
        postgresql:
          enabled: false

        redis:
          enabled: false

        # Use the superset-env secret directly
        envFromSecret: superset-env

        # Disable init containers for now - we'll handle DB setup manually
        init:
          enabled: false

        supersetNode:
          connections:
            db_host: "172.16.0.20"
            db_port: "5432"
            db_user: "superset"
            db_name: "superset"

        configOverrides:
          secret: |
            import os
            SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{os.environ['DB_USER']}:{os.environ['DB_PASS']}@{os.environ['DB_HOST']}:{os.environ.get('DB_PORT', '5432')}/{os.environ['DB_NAME']}"
        worker:
          enabled: false
        beat:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true