apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  source:
    helm:
      values: |
        image:
          registry: ghcr.io
          repository: bitnami/superset
          tag: "5.0.0"   # simple tag avoids the -debian-12-rXX that went missing
          pullPolicy: IfNotPresent
        postgresql:
          enabled: false
        redis:
          enabled: false
        externalDatabase:
          host: 172.16.0.20
          port: 5432
          user: superset
          database: superset
          passwordSecret: superset-externaldb
          passwordSecretKey: db-password
        web:
          initContainers: []
          waitForDB: false
          waitForRedis: false
          replicaCount: 1
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
        worker:
          enabled: false
          initContainers: []
          waitForDB: false
          waitForRedis: false
        scheduler:
          enabled: false
          initContainers: []
          waitForDB: false
          waitForRedis: false