spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: superset
    targetRevision: 5.0.0
    helm:
      parameters: []      # keep empty; values-only so defaults don’t sneak back
      values: |
        postgresql:
          enabled: false

        redis:
          enabled: false

        externalDatabase:
          host: 172.16.0.20
          port: 5432
          user: superset
          database: superset
          passwordSecret: superset-externaldb
          passwordSecretKey: db-password

        web:
          waitForDB: false
          waitForRedis: false
          replicaCount: 1
          resources:
            requests:
              cpu: 10m
              memory: 128Mi

        worker:
          enabled: false
          waitForDB: false
          waitForRedis: false

        scheduler:
          enabled: false
          waitForDB: false
          waitForRedis: false