apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: 0.12.11
    helm:
      values: |
        postgresql:
          enabled: false

        # Read ONLY the DB password from a K8s Secret produced by ExternalSecrets
        extraSecretEnv:
          SUPERSET_DATABASE_PASSWORD:
            secretKeyRef:
              name: superset-db-secret
              key: password

        extraEnv:
          - name: SUPERSET_LOAD_EXAMPLES
            value: "no"

        # Redis with password coming from ExternalSecrets (requires the secret below)
        redis:
          enabled: true
          auth:
            enabled: true
            existingSecret: superset-redis
            existingSecretPasswordKey: redis-password

        # Plain values for now (you can move these to Vault later)
        supersetNode:
          connections:
            db_host: "172.16.0.20"
            db_port: "5432"
            db_user: "superset"
            db_name: "superset"

        init:
          adminUser:
            username: admin
            password: admin
            email: admin@superset.com

        # Prefer SUPERSET_DATABASE_URI if you add it later; otherwise build from fields above
        configOverrides:
          00_db_uri.py: |
            import os
            SQLALCHEMY_DATABASE_URI = os.getenv("SUPERSET_DATABASE_URI")
            if not SQLALCHEMY_DATABASE_URI:
                user = os.getenv("SUPERSET_DATABASE_USER", "{{ .Values.supersetNode.connections.db_user }}")
                pwd  = os.getenv("SUPERSET_DATABASE_PASSWORD", "")
                host = "{{ .Values.supersetNode.connections.db_host }}"
                port = "{{ .Values.supersetNode.connections.db_port }}"
                name = "{{ .Values.supersetNode.connections.db_name }}"
                SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{user}:{pwd}@{host}:{port}/{name}"

        ingress:
          enabled: false # flip to true when ready

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true