apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: superset
    targetRevision: 5.0.0
    helm:
      parameters: []   # keep empty; use values only
      values: |
        image:
          # Docker Hub (Bitnami)
          registry: docker.io
          repository: bitnami/superset
          tag: "5.0.0"         # simple tag; avoids the -debian-12-rXX variant
          pullPolicy: IfNotPresent

        # Disable embedded Postgres/Redis
        postgresql:
          enabled: false
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 16.4.0
        redis:
          enabled: false
          image:
            registry: docker.io
            repository: bitnami/redis
            tag: 7.2.4

        # Turn off the chart’s default init waiters globally
        defaultInitContainers:
          waitForDB:
            enabled: false
          waitForRedis:
            enabled: false

        # Your external DB
        externalDatabase:
          host: 172.16.0.20
          port: 5432
          user: superset
          database: superset
          passwordSecret: superset-externaldb
          passwordSecretKey: db-password

        # Only run the web; small requests so the scheduler stops complaining
        web:
          replicaCount: 1
          resources:
            requests:
              cpu: 50m
              memory: 256Mi

        worker:
          enabled: false
        scheduler:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true