apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://trinodb.github.io/charts
    chart: trino
    targetRevision: 0.29.0
    helm:
      values: |
        server:
          workers: 2
          coordinator:
            jvm:
              maxHeapSize: "4G"
            resources:
              requests:
                memory: "4Gi"
                cpu: "1"
          worker:
            jvm:
              maxHeapSize: "4G"
            resources:
              requests:
                memory: "4Gi"
                cpu: "1"
        service:
          type: ClusterIP
        # Only include built-in catalogs for now
        # We'll add MinIO/Hive later when it's running
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
