apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unity-catalog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tpomavil46/k8s-data-platform.git
    targetRevision: main
    path: charts/unity-catalog
    helm:
      values: |
        server:
          enabled: true
          
          db:
            type: postgresql
            postgresqlConfig:
              host: 172.16.0.20
              port: 5432
              dbName: unitycatalog
              username: unitycatalog
              passwordSecretName: unity-catalog-db-password
              passwordSecretKey: password
          
          deployment:
            replicaCount: 1
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
          
          service:
            type: ClusterIP
            port: 8080
          
          logLevel: info
        
        storage:
          modelStorageRoot: s3://unity-catalog/models
          credentials:
            s3:
              - bucketPath: s3://unity-catalog
                region: us-east-1
                credentialsSecretName: unity-catalog-minio-credentials
        
        ui:
          enabled: true
        
        ingress:
          enabled: true
          host: unitycatalog.tpomaville.com
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
        
        auth:
          enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
