apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unity-catalog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/unitycatalog/unitycatalog.git
    targetRevision: v0.3.0
    path: helm
    helm:
      values: |
        server:
          enabled: true
          
          db:
            type: postgresql
            postgresqlConfig:
              host: 172.16.0.20
              port: 5432
              dbName: unitycatalog
              username: unitycatalog
              passwordSecretName: unity-catalog-db-password
              passwordSecretKey: password
          
          deployment:
            replicaCount: 1
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
          
          service:
            type: ClusterIP
            port: 8080
          
          logLevel: info
        
        storage:
          modelStorageRoot: s3://unity-catalog/models
          credentials:
            s3:
              - bucketPath: s3://unity-catalog
                region: us-east-1  # MinIO doesn't care but required field
                credentialsSecretName: unity-catalog-minio-credentials
        
        ui:
          enabled: false
          deployment:
            image:
              repository: ghcr.io/tpomavil46/unity-catalog-ui
              tag: "0.3.0"
              pullPolicy: Always
            port: 80
            replicaCount: 1
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            
            # Override the container to not use bash (nginx doesn't have it)
            extraContainers:
              - name: ui
                image: ghcr.io/tpomavil46/unity-catalog-ui:0.3.0
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
                    name: ui
                # Let nginx run its default CMD - don't override
                command: []
                args: []
          
          service:
            type: ClusterIP
            port: 80
          
          proxyApiRequests: false
          serverUrl: ""
        
        ingress:
          enabled: true
          host: unitycatalog.tpomaville.com
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          tlsSecretName: unity-catalog-tls
        
        auth:
          enabled: false  # Start without auth, add later
  
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m