apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-runner
  namespace: flink
rules:
  - apiGroups: [""]
    resources: ["pods","pods/log","pods/status","services","configmaps","endpoints","events"]
    verbs: ["get","list","watch","create","delete","update","patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets","deployments"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-runner-binding
  namespace: flink
subjects:
  - kind: ServiceAccount
    name: default
    namespace: flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-runner
