apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-history-server
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-history-server
  namespace: spark
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-history-server
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: spark-history-server
    namespace: spark
roleRef:
  kind: Role
  name: spark-history-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-history-server-conf
  namespace: spark
data:
  spark-defaults.conf: |
    spark.history.fs.logDirectory=s3a://spark-logs/
    spark.history.ui.port=18080
    spark.hadoop.fs.s3a.endpoint=http://172.16.0.20:9000
    spark.hadoop.fs.s3a.path.style.access=true
    spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.connection.ssl.enabled=false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark
  labels:
    app: spark-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      serviceAccountName: spark-history-server
      containers:
      - name: spark-history-server
        image: apache/spark:3.5.0
        command:
          - "/opt/spark/sbin/start-history-server.sh"
        args:
          - "&&"
          - "tail"
          - "-f"
          - "/dev/null"
        ports:
        - containerPort: 18080
          name: http
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "true"
        - name: SPARK_HISTORY_OPTS
          value: "-Dspark.history.fs.logDirectory=s3a://spark-logs/"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spark-minio
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spark-minio
              key: secret-key
        volumeMounts:
        - name: spark-conf
          mountPath: /opt/spark/conf/spark-defaults.conf
          subPath: spark-defaults.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: spark-conf
        configMap:
          name: spark-history-server-conf
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: spark
  labels:
    app: spark-history-server
spec:
  type: ClusterIP
  ports:
  - port: 18080
    targetPort: 18080
    protocol: TCP
    name: http
  selector:
    app: spark-history-server