apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-env
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: superset-env
  # Remove the template section and use data for everything
  data:
    # Static values
    - secretKey: DB_HOST
      remoteRef:
        key: kv/superset
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: kv/superset
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: kv/superset
        property: DB_USER
    - secretKey: DB_NAME
      remoteRef:
        key: kv/superset
        property: DB_NAME
    # Dynamic values from Vault
    - secretKey: DB_PASS
      remoteRef:
        key: kv/superset
        property: password
    - secretKey: SUPERSET_SECRET_KEY
      remoteRef:
        key: kv/superset
        property: SECRET_KEY