apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-env
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: superset-env
    template:
      type: Opaque
      data:
        SUPERSET_SECRET_KEY: "{{ .SECRET_KEY }}"
        # Use consistent naming - just DB_PASS
        DB_PASS: "{{ .password }}"
        DB_HOST: "172.16.0.20"
        DB_PORT: "5432"
        DB_USER: "superset"
        DB_NAME: "superset"
  dataFrom:
    - extract:
        key: kv/superset