apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spark-minio
  namespace: spark
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: spark-minio
    creationPolicy: Owner
  refreshInterval: 1h
  data:
    - secretKey: access-key
      remoteRef:
        key: spark
        property: access_key
    - secretKey: secret-key
      remoteRef:
        key: spark
        property: secret_key
    - secretKey: endpoint
      remoteRef:
        key: spark
        property: endpoint_internal